# Setup
title:            YS[Gy]
tagline:          'CS chobo&#39s CS studying record'
description:      'CS chobo&#39s CS studying record'
url:              https://hyde.getpoole.com
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
